<?php

use App\Models\CatMunicipio;
use Illuminate\Database\Seeder;

class CatMunicipioTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['Alto Orinoco', 1],
            ['Atabapo', 1],
            ['Atures', 1],
            ['Autana', 1],
            ['Maroa', 1],
            ['Manapiare', 1],
            ['Rio Negro', 1],
            ['Fernando De Peñalver', 2],
            ['Francisco Del Carmen Carvajal', 2],
            ['Francisco De Miranda', 2],
            ['Guanta', 2],
            ['Independencia', 2],
            ['Juan Antonio Sotillo', 2],
            ['Juan Manuel Cajigal', 2],
            ['Jose Gregorio Monagas', 2],
            ['Libertad', 2],
            ['Manuel Ezequiel Bruzual', 2],
            ['Pedro Maria Freites', 2],
            ['Piritu', 2],
            ['San Jose De Guanipa', 2],
            ['San Juan De Capistrano', 2],
            ['Santa Ana', 2],
            ['Simon Bolivar', 2],
            ['Simon Rodriguez', 2],
            ['Sir Arthur Mc Gregor', 2],
            ['Diego Bautista Urbaneja', 2],
            ['Achaguas', 3],
            ['Biruaca', 3],
            ['Muñoz', 3],
            ['Paez', 3],
            ['Pedro Camejo', 3],
            ['Romulo Gallegos', 3],
            ['San Fernando', 3],
            ['Bolivar', 4],
            ['Camatagua', 4],
            ['Girardot', 4],
            ['Jose Angel Lamas', 4],
            ['Jose Felix Ribas', 4],
            ['Jose Rafael Revenga', 4],
            ['Libertador', 4],
            ['Mario Briceño Iragorry', 4],
            ['San Casimiro', 4],
            ['San Sebastian', 4],
            ['Santiago Mariño', 4],
            ['Santos Michelena', 4],
            ['Sucre', 4],
            ['Tovar', 4],
            ['Urdaneta', 4],
            ['Zamora', 4],
            ['Francisco Linares Alcantara', 4],
            ['Ocumare De La Costa De Oro', 4],
            ['Alberto Arvelo Torrealba', 5],
            ['Antonio Jose De Sucre', 5],
            ['Arismendi', 5],
            ['Barinas', 5],
            ['Bolivar', 5],
            ['Cruz Paredes', 5],
            ['Ezequiel Zamora', 5],
            ['Obispos', 5],
            ['Pedraza', 5],
            ['Rojas', 5],
            ['Sosa', 5],
            ['Andres Eloy Blanco', 5],
            ['Caroni', 6],
            ['Cedeño', 6],
            ['El Callao', 6],
            ['Gran Sabana', 6],
            ['Heres', 6],
            ['Piar', 6],
            ['Raul Leoni', 6],
            ['Roscio', 6],
            ['Sifontes', 6],
            ['Sucre', 6],
            ['Padre Pedro Chien', 6],
            ['Bejuma', 7],
            ['Carlos Arvelo', 7],
            ['Diego Ibarra', 7],
            ['Guacara', 7],
            ['Juan Jose Mora', 7],
            ['Libertador', 7],
            ['Los Guayos', 7],
            ['Miranda', 7],
            ['Montalban', 7],
            ['Naguanagua', 7],
            ['Puerto Cabello', 7],
            ['San Diego', 7],
            ['San Joaquin', 7],
            ['Valencia', 7],
            ['Anzoategui', 8],
            ['Falcon', 8],
            ['Girardot', 8],
            ['Lima Blanco', 8],
            ['Pao De San Juan Bautista', 8],
            ['Ricaurte', 8],
            ['Romulo Gallegos', 8],
            ['San Carlos', 8],
            ['Tinaco', 8],
            ['Antonio Diaz', 9],
            ['Casacoima', 9],
            ['Pedernales', 9],
            ['Tucupita', 9],
            ['Acosta', 10],
            ['Bolivar', 10],
            ['Buchivacoa', 10],
            ['Cacique Manaure', 10],
            ['Carirubana', 10],
            ['Colina', 10],
            ['Dabajuro', 10],
            ['Democracia', 10],
            ['Falcon', 10],
            ['Federacion', 10],
            ['Jacura', 10],
            ['Los Taques', 10],
            ['Mauroa', 10],
            ['Miranda', 10],
            ['Monseñor Iturriza', 10],
            ['Palmasola', 10],
            ['Petit', 10],
            ['Piritu', 10],
            ['San Francisco', 10],
            ['Silva', 10],
            ['Sucre', 10],
            ['Tocopero', 10],
            ['Union', 10],
            ['Urumaco', 10],
            ['Zamora', 10],
            ['Camaguan', 11],
            ['Chaguaramas', 11],
            ['El Socorro', 11],
            ['San Geronimo De Guayabal', 11],
            ['Leonardo Infante', 11],
            ['Las Mercedes', 11],
            ['Julian Mellado', 11],
            ['Francisco De Miranda', 11],
            ['Jose Tadeo Monagas', 11],
            ['Ortiz', 11],
            ['Jose Felix Ribas', 11],
            ['Juan German Roscio', 11],
            ['San Jose De Guaribe', 11],
            ['Santa Maria De Ipire', 11],
            ['Pedro Zaraza', 11],
            ['Andres Eloy Blanco', 12],
            ['Crespo', 12],
            ['Iribarren', 12],
            ['Jimenez', 12],
            ['Moran', 12],
            ['Palavecino', 12],
            ['Simon Planas', 12],
            ['Torres', 12],
            ['Urdaneta', 12],
            ['Alberto Adriani', 13],
            ['Andres Bello', 13],
            ['Antonio Pinto Salinas', 13],
            ['Aricagua', 13],
            ['Arzobispo Chacon', 13],
            ['Campo Elias', 13],
            ['Caracciolo Parra Olmedo', 13],
            ['Cardenal Quintero', 13],
            ['Guaraque', 13],
            ['Julio Cesar Salas', 13],
            ['Justo Briceño', 13],
            ['Libertador', 13],
            ['Miranda', 13],
            ['Obispo Ramos De Lora', 13],
            ['Padre Noguera', 13],
            ['Pueblo Llano', 13],
            ['Rangel', 13],
            ['Rivas Davila', 13],
            ['Santos Marquina', 13],
            ['Sucre', 13],
            ['Tovar', 13],
            ['Tulio Febres Cordero', 13],
            ['Zea', 13],
            ['Acevedo', 14],
            ['Andres Bello', 14],
            ['Baruta', 14],
            ['Brion', 14],
            ['Buroz', 14],
            ['Carrizal', 14],
            ['Chacao', 14],
            ['Cristobal Rojas', 14],
            ['El Hatillo', 14],
            ['Guaicaipuro', 14],
            ['Independencia', 14],
            ['Lander', 14],
            ['Los Salias', 14],
            ['Paez', 14],
            ['Paz Castillo', 14],
            ['Pedro Gual', 14],
            ['Plaza', 14],
            ['Simon Bolivar', 14],
            ['Sucre', 14],
            ['Urdaneta', 14],
            ['Zamora', 14],
            ['Acosta', 15],
            ['Aguasay', 15],
            ['Bolivar', 15],
            ['Caripe', 15],
            ['Cedeño', 15],
            ['Ezequiel Zamora', 15],
            ['Libertador', 15],
            ['Maturin', 15],
            ['Piar', 15],
            ['Punceres', 15],
            ['Santa Barbara', 15],
            ['Sotillo', 15],
            ['Uracoa', 15],
            ['Antolin Del Campo', 16],
            ['Arismendi', 16],
            ['Diaz', 16],
            ['Garcia', 16],
            ['Gomez', 16],
            ['Maneiro', 16],
            ['Marcano', 16],
            ['Mariño', 16],
            ['Peninsula De Macanao', 16],
            ['Tubores', 16],
            ['Villalba', 16],
            ['Agua Blanca', 17],
            ['Araure', 17],
            ['Esteller', 17],
            ['Guanare', 17],
            ['Guanarito', 17],
            ['Monseñor Jose Vicente De Unda', 17],
            ['Ospino', 17],
            ['Paez', 17],
            ['Papelon', 17],
            ['San Genaro De Boconoito', 17],
            ['San Rafael De Onoto', 17],
            ['Santa Rosalia', 17],
            ['Sucre', 17],
            ['Turen', 17],
            ['Andres Eloy Blanco', 18],
            ['Andres Mata', 18],
            ['Arismendi', 18],
            ['Benitez', 18],
            ['Bermudez', 18],
            ['Bolivar', 18],
            ['Cajigal', 18],
            ['Cruz Salmeron Acosta', 18],
            ['Libertador', 18],
            ['Mariño', 18],
            ['Mejia', 18],
            ['Montes', 18],
            ['Ribero', 18],
            ['Sucre', 18],
            ['Valdez', 18],
            ['Andres Bello', 19],
            ['Antonio Romulo Costa', 19],
            ['Ayacucho', 19],
            ['Bolivar', 19],
            ['Cardenas', 19],
            ['Cordoba', 19],
            ['Fernandez Feo', 19],
            ['Francisco De Miranda', 19],
            ['Garcia De Hevia', 19],
            ['Guasimos', 19],
            ['Independencia', 19],
            ['Jauregui', 19],
            ['Jose Maria Vargas', 19],
            ['Junin', 19],
            ['Libertad', 19],
            ['Libertador', 19],
            ['Lobatera', 19],
            ['Michelena', 19],
            ['Panamericano', 19],
            ['Pedro Maria Ureña', 19],
            ['Rafael Urdaneta', 19],
            ['Samuel Dario Maldonado', 19],
            ['San Cristobal', 19],
            ['Seboruco', 19],
            ['Simon Rodriguez', 19],
            ['Sucre', 19],
            ['Torbes', 19],
            ['Uribante', 19],
            ['San Judas Tadeo', 19],
            ['Andres Bello', 20],
            ['Bocono', 20],
            ['Bolivar', 20],
            ['Candelaria', 20],
            ['Carache', 20],
            ['Escuque', 20],
            ['Jose Felipe Marquez Cañizalez', 20],
            ['Juan Vicente Campo Elias', 20],
            ['La Ceiba', 20],
            ['Miranda', 20],
            ['Monte Carmelo', 20],
            ['Motatan', 20],
            ['Pampan', 20],
            ['Pampanito', 20],
            ['Rafael Rangel', 20],
            ['San Rafael De Carvajal', 20],
            ['Sucre', 20],
            ['Trujillo', 20],
            ['Urdaneta', 20],
            ['Valera', 20],
            ['Aristides Bastidas', 21],
            ['Bolivar', 21],
            ['Bruzual', 21],
            ['Cocorote', 21],
            ['Independencia', 21],
            ['Jose Antonio Paez', 21],
            ['La Trinidad', 21],
            ['Manuel Monge', 21],
            ['Nirgua', 21],
            ['Peña', 21],
            ['San Felipe', 21],
            ['Sucre', 21],
            ['Urachiche', 21],
            ['Veroes', 21],
            ['Almirante Padilla', 22],
            ['Baralt', 22],
            ['Cabimas', 22],
            ['Catatumbo', 22],
            ['Colon', 22],
            ['Francisco Javier Pulgar', 22],
            ['Jesus Enrique Lossada', 22],
            ['Jesus Maria Semprun', 22],
            ['La Cañada De Urdaneta', 22],
            ['Lagunillas', 22],
            ['Machiques De Perija', 22],
            ['Mara', 22],
            ['Maracaibo', 22],
            ['Miranda', 22],
            ['Paez', 22],
            ['Rosario De Perija', 22],
            ['San Francisco', 22],
            ['Santa Rita', 22],
            ['Simon Bolivar', 22],
            ['Sucre', 22],
            ['Valmore Rodriguez', 22],
            ['Libertador', 24],
            ['Vargas', 25]
        ];
        foreach ($data as $key => $value) {
            CatMunicipio::create(['description' =>$data[$key][0],'cat_estado_id' =>$data[$key][1]]);
        }
    }
}
