export let getAll = ()=> {
    //return await get( location.origin+"/cat_user_estado/index")
    return [
        {
            "id": 1,
            "description": "Alto Orinoco",
            "cat_estado_id": 1,
            "active": 1,
        },
        {
            "id": 2,
            "description": "Atabapo",
            "cat_estado_id": 1,
            "active": 1,
        },
        {
            "id": 3,
            "description": "Atures",
            "cat_estado_id": 1,
            "active": 1,
        },
        {
            "id": 4,
            "description": "Autana",
            "cat_estado_id": 1,
            "active": 1,
        },
        {
            "id": 5,
            "description": "Maroa",
            "cat_estado_id": 1,
            "active": 1,
        },
        {
            "id": 6,
            "description": "Manapiare",
            "cat_estado_id": 1,
            "active": 1,
        },
        {
            "id": 7,
            "description": "Rio Negro",
            "cat_estado_id": 1,
            "active": 1,
        },
        {
            "id": 8,
            "description": "Fernando De Peñalver",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 9,
            "description": "Francisco Del Carmen Carvajal",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 10,
            "description": "Francisco De Miranda",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 11,
            "description": "Guanta",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 12,
            "description": "Independencia",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 13,
            "description": "Juan Antonio Sotillo",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 14,
            "description": "Juan Manuel Cajigal",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 15,
            "description": "Jose Gregorio Monagas",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 16,
            "description": "Libertad",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 17,
            "description": "Manuel Ezequiel Bruzual",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 18,
            "description": "Pedro Maria Freites",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 19,
            "description": "Piritu",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 20,
            "description": "San Jose De Guanipa",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 21,
            "description": "San Juan De Capistrano",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 22,
            "description": "Santa Ana",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 23,
            "description": "Simon Bolivar",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 24,
            "description": "Simon Rodriguez",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 25,
            "description": "Sir Arthur Mc Gregor",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 26,
            "description": "Diego Bautista Urbaneja",
            "cat_estado_id": 2,
            "active": 1,
        },
        {
            "id": 27,
            "description": "Achaguas",
            "cat_estado_id": 3,
            "active": 1,
        },
        {
            "id": 28,
            "description": "Biruaca",
            "cat_estado_id": 3,
            "active": 1,
        },
        {
            "id": 29,
            "description": "Muñoz",
            "cat_estado_id": 3,
            "active": 1,
        },
        {
            "id": 30,
            "description": "Paez",
            "cat_estado_id": 3,
            "active": 1,
        },
        {
            "id": 31,
            "description": "Pedro Camejo",
            "cat_estado_id": 3,
            "active": 1,
        },
        {
            "id": 32,
            "description": "Romulo Gallegos",
            "cat_estado_id": 3,
            "active": 1,
        },
        {
            "id": 33,
            "description": "San Fernando",
            "cat_estado_id": 3,
            "active": 1,
        },
        {
            "id": 34,
            "description": "Bolivar",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 35,
            "description": "Camatagua",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 36,
            "description": "Girardot",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 37,
            "description": "Jose Angel Lamas",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 38,
            "description": "Jose Felix Ribas",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 39,
            "description": "Jose Rafael Revenga",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 40,
            "description": "Libertador",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 41,
            "description": "Mario Briceño Iragorry",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 42,
            "description": "San Casimiro",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 43,
            "description": "San Sebastian",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 44,
            "description": "Santiago Mariño",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 45,
            "description": "Santos Michelena",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 46,
            "description": "Sucre",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 47,
            "description": "Tovar",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 48,
            "description": "Urdaneta",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 49,
            "description": "Zamora",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 50,
            "description": "Francisco Linares Alcantara",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 51,
            "description": "Ocumare De La Costa De Oro",
            "cat_estado_id": 4,
            "active": 1,
        },
        {
            "id": 52,
            "description": "Alberto Arvelo Torrealba",
            "cat_estado_id": 5,
            "active": 1,
        },
        {
            "id": 53,
            "description": "Antonio Jose De Sucre",
            "cat_estado_id": 5,
            "active": 1,
        },
        {
            "id": 54,
            "description": "Arismendi",
            "cat_estado_id": 5,
            "active": 1,
        },
        {
            "id": 55,
            "description": "Barinas",
            "cat_estado_id": 5,
            "active": 1,
        },
        {
            "id": 56,
            "description": "Bolivar",
            "cat_estado_id": 5,
            "active": 1,
        },
        {
            "id": 57,
            "description": "Cruz Paredes",
            "cat_estado_id": 5,
            "active": 1,
        },
        {
            "id": 58,
            "description": "Ezequiel Zamora",
            "cat_estado_id": 5,
            "active": 1,
        },
        {
            "id": 59,
            "description": "Obispos",
            "cat_estado_id": 5,
            "active": 1,
        },
        {
            "id": 60,
            "description": "Pedraza",
            "cat_estado_id": 5,
            "active": 1,
        },
        {
            "id": 61,
            "description": "Rojas",
            "cat_estado_id": 5,
            "active": 1,
        },
        {
            "id": 62,
            "description": "Sosa",
            "cat_estado_id": 5,
            "active": 1,
        },
        {
            "id": 63,
            "description": "Andres Eloy Blanco",
            "cat_estado_id": 5,
            "active": 1,
        },
        {
            "id": 64,
            "description": "Caroni",
            "cat_estado_id": 6,
            "active": 1,
        },
        {
            "id": 65,
            "description": "Cedeño",
            "cat_estado_id": 6,
            "active": 1,
        },
        {
            "id": 66,
            "description": "El Callao",
            "cat_estado_id": 6,
            "active": 1,
        },
        {
            "id": 67,
            "description": "Gran Sabana",
            "cat_estado_id": 6,
            "active": 1,
        },
        {
            "id": 68,
            "description": "Heres",
            "cat_estado_id": 6,
            "active": 1,
        },
        {
            "id": 69,
            "description": "Piar",
            "cat_estado_id": 6,
            "active": 1,
        },
        {
            "id": 70,
            "description": "Raul Leoni",
            "cat_estado_id": 6,
            "active": 1,
        },
        {
            "id": 71,
            "description": "Roscio",
            "cat_estado_id": 6,
            "active": 1,
        },
        {
            "id": 72,
            "description": "Sifontes",
            "cat_estado_id": 6,
            "active": 1,
        },
        {
            "id": 73,
            "description": "Sucre",
            "cat_estado_id": 6,
            "active": 1,
        },
        {
            "id": 74,
            "description": "Padre Pedro Chien",
            "cat_estado_id": 6,
            "active": 1,
        },
        {
            "id": 75,
            "description": "Bejuma",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 76,
            "description": "Carlos Arvelo",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 77,
            "description": "Diego Ibarra",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 78,
            "description": "Guacara",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 79,
            "description": "Juan Jose Mora",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 80,
            "description": "Libertador",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 81,
            "description": "Los Guayos",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 82,
            "description": "Miranda",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 83,
            "description": "Montalban",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 84,
            "description": "Naguanagua",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 85,
            "description": "Puerto Cabello",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 86,
            "description": "San Diego",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 87,
            "description": "San Joaquin",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 88,
            "description": "Valencia",
            "cat_estado_id": 7,
            "active": 1,
        },
        {
            "id": 89,
            "description": "Anzoategui",
            "cat_estado_id": 8,
            "active": 1,
        },
        {
            "id": 90,
            "description": "Falcon",
            "cat_estado_id": 8,
            "active": 1,
        },
        {
            "id": 91,
            "description": "Girardot",
            "cat_estado_id": 8,
            "active": 1,
        },
        {
            "id": 92,
            "description": "Lima Blanco",
            "cat_estado_id": 8,
            "active": 1,
        },
        {
            "id": 93,
            "description": "Pao De San Juan Bautista",
            "cat_estado_id": 8,
            "active": 1,
        },
        {
            "id": 94,
            "description": "Ricaurte",
            "cat_estado_id": 8,
            "active": 1,
        },
        {
            "id": 95,
            "description": "Romulo Gallegos",
            "cat_estado_id": 8,
            "active": 1,
        },
        {
            "id": 96,
            "description": "San Carlos",
            "cat_estado_id": 8,
            "active": 1,
        },
        {
            "id": 97,
            "description": "Tinaco",
            "cat_estado_id": 8,
            "active": 1,
        },
        {
            "id": 98,
            "description": "Antonio Diaz",
            "cat_estado_id": 9,
            "active": 1,
        },
        {
            "id": 99,
            "description": "Casacoima",
            "cat_estado_id": 9,
            "active": 1,
        },
        {
            "id": 100,
            "description": "Pedernales",
            "cat_estado_id": 9,
            "active": 1,
        },
        {
            "id": 101,
            "description": "Tucupita",
            "cat_estado_id": 9,
            "active": 1,
        },
        {
            "id": 102,
            "description": "Acosta",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 103,
            "description": "Bolivar",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 104,
            "description": "Buchivacoa",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 105,
            "description": "Cacique Manaure",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 106,
            "description": "Carirubana",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 107,
            "description": "Colina",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 108,
            "description": "Dabajuro",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 109,
            "description": "Democracia",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 110,
            "description": "Falcon",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 111,
            "description": "Federacion",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 112,
            "description": "Jacura",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 113,
            "description": "Los Taques",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 114,
            "description": "Mauroa",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 115,
            "description": "Miranda",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 116,
            "description": "Monseñor Iturriza",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 117,
            "description": "Palmasola",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 118,
            "description": "Petit",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 119,
            "description": "Piritu",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 120,
            "description": "San Francisco",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 121,
            "description": "Silva",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 122,
            "description": "Sucre",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 123,
            "description": "Tocopero",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 124,
            "description": "Union",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 125,
            "description": "Urumaco",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 126,
            "description": "Zamora",
            "cat_estado_id": 10,
            "active": 1,
        },
        {
            "id": 127,
            "description": "Camaguan",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 128,
            "description": "Chaguaramas",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 129,
            "description": "El Socorro",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 130,
            "description": "San Geronimo De Guayabal",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 131,
            "description": "Leonardo Infante",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 132,
            "description": "Las Mercedes",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 133,
            "description": "Julian Mellado",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 134,
            "description": "Francisco De Miranda",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 135,
            "description": "Jose Tadeo Monagas",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 136,
            "description": "Ortiz",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 137,
            "description": "Jose Felix Ribas",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 138,
            "description": "Juan German Roscio",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 139,
            "description": "San Jose De Guaribe",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 140,
            "description": "Santa Maria De Ipire",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 141,
            "description": "Pedro Zaraza",
            "cat_estado_id": 11,
            "active": 1,
        },
        {
            "id": 142,
            "description": "Andres Eloy Blanco",
            "cat_estado_id": 12,
            "active": 1,
        },
        {
            "id": 143,
            "description": "Crespo",
            "cat_estado_id": 12,
            "active": 1,
        },
        {
            "id": 144,
            "description": "Iribarren",
            "cat_estado_id": 12,
            "active": 1,
        },
        {
            "id": 145,
            "description": "Jimenez",
            "cat_estado_id": 12,
            "active": 1,
        },
        {
            "id": 146,
            "description": "Moran",
            "cat_estado_id": 12,
            "active": 1,
        },
        {
            "id": 147,
            "description": "Palavecino",
            "cat_estado_id": 12,
            "active": 1,
        },
        {
            "id": 148,
            "description": "Simon Planas",
            "cat_estado_id": 12,
            "active": 1,
        },
        {
            "id": 149,
            "description": "Torres",
            "cat_estado_id": 12,
            "active": 1,
        },
        {
            "id": 150,
            "description": "Urdaneta",
            "cat_estado_id": 12,
            "active": 1,
        },
        {
            "id": 151,
            "description": "Alberto Adriani",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 152,
            "description": "Andres Bello",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 153,
            "description": "Antonio Pinto Salinas",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 154,
            "description": "Aricagua",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 155,
            "description": "Arzobispo Chacon",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 156,
            "description": "Campo Elias",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 157,
            "description": "Caracciolo Parra Olmedo",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 158,
            "description": "Cardenal Quintero",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 159,
            "description": "Guaraque",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 160,
            "description": "Julio Cesar Salas",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 161,
            "description": "Justo Briceño",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 162,
            "description": "Libertador",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 163,
            "description": "Miranda",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 164,
            "description": "Obispo Ramos De Lora",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 165,
            "description": "Padre Noguera",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 166,
            "description": "Pueblo Llano",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 167,
            "description": "Rangel",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 168,
            "description": "Rivas Davila",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 169,
            "description": "Santos Marquina",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 170,
            "description": "Sucre",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 171,
            "description": "Tovar",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 172,
            "description": "Tulio Febres Cordero",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 173,
            "description": "Zea",
            "cat_estado_id": 13,
            "active": 1,
        },
        {
            "id": 174,
            "description": "Acevedo",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 175,
            "description": "Andres Bello",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 176,
            "description": "Baruta",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 177,
            "description": "Brion",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 178,
            "description": "Buroz",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 179,
            "description": "Carrizal",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 180,
            "description": "Chacao",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 181,
            "description": "Cristobal Rojas",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 182,
            "description": "El Hatillo",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 183,
            "description": "Guaicaipuro",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 184,
            "description": "Independencia",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 185,
            "description": "Lander",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 186,
            "description": "Los Salias",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 187,
            "description": "Paez",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 188,
            "description": "Paz Castillo",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 189,
            "description": "Pedro Gual",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 190,
            "description": "Plaza",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 191,
            "description": "Simon Bolivar",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 192,
            "description": "Sucre",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 193,
            "description": "Urdaneta",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 194,
            "description": "Zamora",
            "cat_estado_id": 14,
            "active": 1,
        },
        {
            "id": 195,
            "description": "Acosta",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 196,
            "description": "Aguasay",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 197,
            "description": "Bolivar",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 198,
            "description": "Caripe",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 199,
            "description": "Cedeño",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 200,
            "description": "Ezequiel Zamora",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 201,
            "description": "Libertador",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 202,
            "description": "Maturin",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 203,
            "description": "Piar",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 204,
            "description": "Punceres",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 205,
            "description": "Santa Barbara",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 206,
            "description": "Sotillo",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 207,
            "description": "Uracoa",
            "cat_estado_id": 15,
            "active": 1,
        },
        {
            "id": 208,
            "description": "Antolin Del Campo",
            "cat_estado_id": 16,
            "active": 1,
        },
        {
            "id": 209,
            "description": "Arismendi",
            "cat_estado_id": 16,
            "active": 1,
        },
        {
            "id": 210,
            "description": "Diaz",
            "cat_estado_id": 16,
            "active": 1,
        },
        {
            "id": 211,
            "description": "Garcia",
            "cat_estado_id": 16,
            "active": 1,
        },
        {
            "id": 212,
            "description": "Gomez",
            "cat_estado_id": 16,
            "active": 1,
        },
        {
            "id": 213,
            "description": "Maneiro",
            "cat_estado_id": 16,
            "active": 1,
        },
        {
            "id": 214,
            "description": "Marcano",
            "cat_estado_id": 16,
            "active": 1,
        },
        {
            "id": 215,
            "description": "Mariño",
            "cat_estado_id": 16,
            "active": 1,
        },
        {
            "id": 216,
            "description": "Peninsula De Macanao",
            "cat_estado_id": 16,
            "active": 1,
        },
        {
            "id": 217,
            "description": "Tubores",
            "cat_estado_id": 16,
            "active": 1,
        },
        {
            "id": 218,
            "description": "Villalba",
            "cat_estado_id": 16,
            "active": 1,
        },
        {
            "id": 219,
            "description": "Agua Blanca",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 220,
            "description": "Araure",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 221,
            "description": "Esteller",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 222,
            "description": "Guanare",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 223,
            "description": "Guanarito",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 224,
            "description": "Monseñor Jose Vicente De Unda",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 225,
            "description": "Ospino",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 226,
            "description": "Paez",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 227,
            "description": "Papelon",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 228,
            "description": "San Genaro De Boconoito",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 229,
            "description": "San Rafael De Onoto",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 230,
            "description": "Santa Rosalia",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 231,
            "description": "Sucre",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 232,
            "description": "Turen",
            "cat_estado_id": 17,
            "active": 1,
        },
        {
            "id": 233,
            "description": "Andres Eloy Blanco",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 234,
            "description": "Andres Mata",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 235,
            "description": "Arismendi",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 236,
            "description": "Benitez",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 237,
            "description": "Bermudez",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 238,
            "description": "Bolivar",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 239,
            "description": "Cajigal",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 240,
            "description": "Cruz Salmeron Acosta",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 241,
            "description": "Libertador",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 242,
            "description": "Mariño",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 243,
            "description": "Mejia",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 244,
            "description": "Montes",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 245,
            "description": "Ribero",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 246,
            "description": "Sucre",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 247,
            "description": "Valdez",
            "cat_estado_id": 18,
            "active": 1,
        },
        {
            "id": 248,
            "description": "Andres Bello",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 249,
            "description": "Antonio Romulo Costa",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 250,
            "description": "Ayacucho",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 251,
            "description": "Bolivar",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 252,
            "description": "Cardenas",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 253,
            "description": "Cordoba",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 254,
            "description": "Fernandez Feo",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 255,
            "description": "Francisco De Miranda",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 256,
            "description": "Garcia De Hevia",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 257,
            "description": "Guasimos",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 258,
            "description": "Independencia",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 259,
            "description": "Jauregui",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 260,
            "description": "Jose Maria Vargas",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 261,
            "description": "Junin",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 262,
            "description": "Libertad",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 263,
            "description": "Libertador",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 264,
            "description": "Lobatera",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 265,
            "description": "Michelena",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 266,
            "description": "Panamericano",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 267,
            "description": "Pedro Maria Ureña",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 268,
            "description": "Rafael Urdaneta",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 269,
            "description": "Samuel Dario Maldonado",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 270,
            "description": "San Cristobal",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 271,
            "description": "Seboruco",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 272,
            "description": "Simon Rodriguez",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 273,
            "description": "Sucre",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 274,
            "description": "Torbes",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 275,
            "description": "Uribante",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 276,
            "description": "San Judas Tadeo",
            "cat_estado_id": 19,
            "active": 1,
        },
        {
            "id": 277,
            "description": "Andres Bello",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 278,
            "description": "Bocono",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 279,
            "description": "Bolivar",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 280,
            "description": "Candelaria",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 281,
            "description": "Carache",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 282,
            "description": "Escuque",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 283,
            "description": "Jose Felipe Marquez Cañizalez",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 284,
            "description": "Juan Vicente Campo Elias",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 285,
            "description": "La Ceiba",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 286,
            "description": "Miranda",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 287,
            "description": "Monte Carmelo",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 288,
            "description": "Motatan",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 289,
            "description": "Pampan",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 290,
            "description": "Pampanito",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 291,
            "description": "Rafael Rangel",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 292,
            "description": "San Rafael De Carvajal",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 293,
            "description": "Sucre",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 294,
            "description": "Trujillo",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 295,
            "description": "Urdaneta",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 296,
            "description": "Valera",
            "cat_estado_id": 20,
            "active": 1,
        },
        {
            "id": 297,
            "description": "Aristides Bastidas",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 298,
            "description": "Bolivar",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 299,
            "description": "Bruzual",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 300,
            "description": "Cocorote",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 301,
            "description": "Independencia",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 302,
            "description": "Jose Antonio Paez",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 303,
            "description": "La Trinidad",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 304,
            "description": "Manuel Monge",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 305,
            "description": "Nirgua",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 306,
            "description": "Peña",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 307,
            "description": "San Felipe",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 308,
            "description": "Sucre",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 309,
            "description": "Urachiche",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 310,
            "description": "Veroes",
            "cat_estado_id": 21,
            "active": 1,
        },
        {
            "id": 311,
            "description": "Almirante Padilla",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 312,
            "description": "Baralt",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 313,
            "description": "Cabimas",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 314,
            "description": "Catatumbo",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 315,
            "description": "Colon",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 316,
            "description": "Francisco Javier Pulgar",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 317,
            "description": "Jesus Enrique Lossada",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 318,
            "description": "Jesus Maria Semprun",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 319,
            "description": "La Cañada De Urdaneta",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 320,
            "description": "Lagunillas",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 321,
            "description": "Machiques De Perija",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 322,
            "description": "Mara",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 323,
            "description": "Maracaibo",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 324,
            "description": "Miranda",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 325,
            "description": "Paez",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 326,
            "description": "Rosario De Perija",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 327,
            "description": "San Francisco",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 328,
            "description": "Santa Rita",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 329,
            "description": "Simon Bolivar",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 330,
            "description": "Sucre",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 331,
            "description": "Valmore Rodriguez",
            "cat_estado_id": 22,
            "active": 1,
        },
        {
            "id": 332,
            "description": "Libertador",
            "cat_estado_id": 24,
            "active": 1,
        },
        {
            "id": 333,
            "description": "Vargas",
            "cat_estado_id": 25,
            "active": 1,
        }
    ]
}
export let getOne = (id)=> {
    return getAll().find(item=>Number(item.id) === Number(id))
}